#page title
page_title                                : BeMyVoice â€“ A Free and Easy To Use AAC Text-to-Speech App                                      # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1542008796                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : BeMyVoice is an app for Augmentative and Alternative Communication (AAC) that allows people with speaking disabilities to communicate by pressing speech buttons with pictograms.

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Alexander Klauer
your_link                                 :
your_city                                 :
email_address                             : alex@bemyvoice.app
facebook_username                         :
instagram_username                        :
twitter_username                          : BeMyVoice_AAC
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : High quality voices
    description                           : of 27 languages, each with customizable pitch and speed
    fontawesome_icon_name                 : volume-up

  - title                                 : Professional pictogram library
    description                           : with over 10,000+ professionally made AAC pictograms
    fontawesome_icon_name                 : images

  - title                                 : Completely free
    description                           : because AAC technology should be available to as many people as possible, no hidden costs, no ads
    fontawesome_icon_name                 : money-bill-wave

  - title                                 : Offline translation
    description                           : allows to switch the language of the whole board and speak in another language with automatic offline translation
    fontawesome_icon_name                 : language

  - title                                 : Flexible board height & width
    description                           : lets you choose between grids with either 4x3, 8x6, 12x9 or 16x12 speech buttons
    fontawesome_icon_name                 : arrows-alt

  - title                                 : Unlimited subfolders
    description                           : help organizing speech buttons to make them easily findable
    fontawesome_icon_name                 : folder


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : black
app_price_color                           : black
app_description_color                     : black

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#d14337"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
